get:
  summary: Evolution of Ethereum mining equipment efficiency
  tags:
    - ETH/Charts
  responses:
    200:
      description: Successful operation
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                efficiency:
                  type: number
                timestamp:
                  type: number

