get:
  summary: Ethereum Consensus Client Distribution
  tags:
    - Ethereum/Charts
  responses:
    200:
      description: Successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Prysm
                    x:
                      type: number
                      example: 1644273000
                    y:
                      type: number
                      example: 2209
