get:
  summary: Ethereum Node Distribution
  tags:
    - Ethereum/Charts
  responses:
    200:
      description: Successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  properties:
                    code:
                      type: string
                    name:
                      type: string
                    flag:
                      type: string
                    number_of_nodes:
                      type: number
                    country_share:
                      type: number
