get:
  summary: "Ethereum power demand: Legacy vs Future"
  tags:
    - Ethereum/Charts
  responses:
    200:
      description: Successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Ethereum 1.0
                    guess_power:
                      type: number
                      example: 1804.32
