get:
  summary: Total number of active validators
  tags:
    - Ethereum/Charts
  parameters:
    - in: path
      name: date
      schema:
        type: string
      required: false
  responses:
    200:
      description: Successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  properties:
                    x:
                      type: number
                    y:
                      type: number
