blockchain_data:
    dbname: yourdb
    user: youruser
    password: yourpassword
    host: 127.0.0.1
    port: 5432
custom_data:
    dbname: yourdb
    user: youruser
    password: yourpassword
    host: 127.0.0.1
    port: 5432
webhook: "https://yourwebhookurl.com"
webhook_err: "https://yourwebhookurl.com"

api_eia_gov:
  api_key: "api key"