from console.commands.charts.save_mining_map_countries import handle as save_mining_map_countries
from console.commands.charts.save_mining_map_provinces import handle as save_mining_map_provinces
from console.commands.charts.save_mining_area_countries import handle as save_mining_area_countries
from console.commands.charts.save_mining_area_provinces import handle as save_mining_area_provinces
from console.commands.charts.calc_bitcoin_emission_intensity import handle as calc_bitcoin_emission_intensity
from console.commands.charts.calc_bitcoin_greenhouse_gas_emissions import \
    handle as calc_bitcoin_greenhouse_gas_emissions
from console.commands.charts.save_mining_revenue_from_fee import handle as save_mining_revenue_from_fee
from console.commands.charts.energy_efficiency_of_bitcoin_mining_hardware import \
    handle as energy_efficiency_of_bitcoin_mining_hardware
