from commands.charts.save_mining_map_countries import handle as save_mining_map_countries
from commands.charts.save_mining_map_provinces import handle as save_mining_map_provinces
from commands.charts.save_mining_area_countries import handle as save_mining_area_countries
from commands.charts.save_mining_area_provinces import handle as save_mining_area_provinces
