get:
  summary: Miners
  tags:
    - Charts
  responses:
    200:
      description: Successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    x:
                      type: integer
                    y:
                      type: number
