get:
  summary: Evolution of Ethereum mining equipment efficiency, Mh/J
  tags:
    - Ethereum 1.0/Charts
  responses:
    200:
      description: Successful operation
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                x:
                  type: number
                y:
                  type: number

