from .network_power_demand import NetworkPowerDemandDto
from .total_electricity_consumption import TotalElectricityConsumptionDto
from .machine_efficiency import MachineEfficiencyDto
from .average_machine_efficiency import AverageMachineEfficiencyDto
from .mining_equipment_efficiency import MiningEquipmentEfficiencyDto
from .profitability_threshold import ProfitabilityThresholdDto
