from console.commands.eth.pow_compare_sources import handle as pow_compare_sources
from console.commands.eth.sync_coinmetrics import handle as sync_coinmetrics
from console.commands.eth.compare_datasource import handle as compare_datasource
from console.commands.eth.pos_calc_electricity import handle as pos_calc_electricity
from console.commands.eth.pos_sync_nodes import handle as pos_sync_nodes
from console.commands.eth.pos_sync_nodes_distribution import handle as pos_sync_nodes_distribution
from console.commands.eth.live_data import handle as live_data
from console.commands.eth.pos_ghg_emissions import handle as pos_ghg_emissions
from console.commands.eth.pow_ghg_emissions import handle as pow_ghg_emissions
