from .network_power_demand import NetworkPowerDemandDto
from .monthly_total_electricity_consumption import MonthlyTotalElectricityConsumptionDto
from .yearly_total_electricity_consumption import YearlyTotalElectricityConsumptionDto
