name: Cbeci API demo server deploy
on: 
  push:
    branches:
      - develop
    paths-ignore:
      - 'frontend/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: CLI commands for deploy
      uses: appleboy/ssh-action@master
      env:
        SHA: ${{ github.sha }}
      with:
        host: ${{ secrets.DEMO_SERVER_HOST }}
        username: cbeci
        port: 22
        envs: SHA
        script_stop: true
        key:  ${{ secrets.DEMO_CBECI_USER_KEY }}
        script: |
          export PATH="/home/cbeci/.pyenv/bin:$PATH"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          source $HOME/.poetry/env
          cd ${{ secrets.DEMO_API_PROJECT_PATH }}
          rm -rf releases/$SHA
          mkdir releases/$SHA
          cd releases/$SHA
          ssh-agent bash -c 'ssh-add /home/cbeci/.ssh/id_rsa_mining_energy_consumption; git clone git@github.com:dektox/mining_energy_consumption.git .'
          git checkout $SHA
          ln -s ${{ secrets.DEMO_API_PROJECT_PATH }}/.env .env
          ln -s ${{ secrets.DEMO_API_PROJECT_PATH }}/CONFIG.yml CONFIG.yml
          ln -s ${{ secrets.DEMO_API_PROJECT_PATH }}/service-account-cert.ccaf-afea-test.json storage/firebase/service-account-cert.ccaf-afea-test.json
          poetry install
          cd api
          poetry run pytest tests
          rm -rf ${{ secrets.DEMO_API_PROJECT_PATH }}/actual
          ln -s ${{ secrets.DEMO_API_PROJECT_PATH }}/releases/$SHA ${{ secrets.DEMO_API_PROJECT_PATH }}/actual
          sudo /usr/sbin/service demo.cbeci_api restart
    - name: Remove failed release
      uses: appleboy/ssh-action@master
      if: failure()
      env:
        SHA: ${{ github.sha }}
      with:
        host: ${{ secrets.DEMO_SERVER_HOST }}
        username: atlas
        port: 22
        envs: SHA
        script_stop: true
        key: ${{ secrets.DEMO_CBECI_USER_KEY }}
        script: |
          rm -rf ${{ secrets.DEMO_API_PROJECT_PATH }}/releases/$SHA
