name: Cbeci frontend production server deploy
on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
jobs:
  deploy:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: CLI commands for build project
      uses: appleboy/ssh-action@master
      env:
        SHA: ${{ github.sha }}
      with:
        host: ${{ secrets.DEMO_SERVER_HOST }}
        username: cbeci
        port: 22
        envs: SHA
        script_stop: true
        key:  ${{ secrets.CBECI_USER_KEY }}
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd ${{ secrets.PRODUCTION_FRONTEND_BUILD_PATH }}
          rm -rf releases/$SHA
          mkdir releases/$SHA
          cd releases/$SHA
          ssh-agent bash -c 'ssh-add /home/cbeci/.ssh/id_rsa_mining_energy_consumption; git clone git@github.com:dektox/mining_energy_consumption.git .'
          git checkout $SHA
          cd frontend
          npm i
          cp ${{ secrets.PRODUCTION_FRONTEND_BUILD_PATH }}/.env .env
          npm run build
          ssh cbeci@${{ secrets.PRODUCTION_SERVER_HOST }} "rm -rf ${{ secrets.PRODUCTION_FRONTEND_BUILD_PATH }}/releases/$SHA"
          scp -r ${{ secrets.PRODUCTION_FRONTEND_BUILD_PATH }}/releases/$SHA cbeci@${{ secrets.PRODUCTION_SERVER_HOST }}:${{ secrets.PRODUCTION_FRONTEND_BUILD_PATH }}/releases
    - uses: actions/checkout@v1
    - name: CLI commands for launch built project on live server
      uses: appleboy/ssh-action@master
      env:
        SHA: ${{ github.sha }}
      with:
        host: ${{ secrets.PRODUCTION_SERVER_HOST }}
        username: cbeci
        port: 22
        envs: SHA
        script_stop: true
        key:  ${{ secrets.CBECI_USER_KEY }}
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd ${{ secrets.PRODUCTION_FRONTEND_BUILD_PATH }}
          rm -rf actual
          ln -s ${{ secrets.PRODUCTION_FRONTEND_BUILD_PATH }}/releases/$SHA ${{ secrets.PRODUCTION_FRONTEND_BUILD_PATH }}/actual
          pm2 restart pm2.config.json
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Gcloud deploy
      run: |
        export PROJECT=ccaf-afea
        export FAMILY=cbeci-prod-images
        export ZONE=europe-west2-b
        export STORAGE_LOCATION=europe-west2
        export SOURCE_DISK=cbeci-production
        export MACHINE_IMAGE=cbeci-prod-image-${{ steps.vars.outputs.sha_short }}
        export INSTANCE_TEMPLATE=cbeci-prod-template-${{ steps.vars.outputs.sha_short }}
        export INSTANCE_GROUP=cbeci-prod-group
        
        gcloud compute images create $MACHINE_IMAGE --project=$PROJECT --family=$FAMILY --source-disk=$SOURCE_DISK --source-disk-zone=$ZONE --labels=env=prod,cbeci-prod-image=1 --storage-location=$STORAGE_LOCATION --force
        gcloud --quiet beta compute --project=$PROJECT instance-templates create $INSTANCE_TEMPLATE --machine-type=e2-medium --network=projects/ccaf-afea/global/networks/default --network-tier=PREMIUM --metadata="env=prod,cbeci-prod-web=1,startup-script=crontab -u cbeci -r" --maintenance-policy=MIGRATE --service-account=756071129183-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --tags=http-server,https-server --image=$MACHINE_IMAGE --image-project=$PROJECT --boot-disk-size=32GB --boot-disk-type=pd-balanced --boot-disk-device-name=$INSTANCE_TEMPLATE --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
        gcloud compute instance-groups managed set-instance-template $INSTANCE_GROUP --project=$PROJECT --template=$INSTANCE_TEMPLATE --zone=$ZONE
        gcloud beta compute instance-groups managed rolling-action replace $INSTANCE_GROUP --project=$PROJECT --zone=$ZONE --quiet
